# Generated by Django 5.2 on 2025-05-20 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='date_purchased',
            new_name='purchase_date',
        ),
    ]
